import React from 'react';
import { Loader2, Copy, Check } from 'lucide-react';
import { Button } from './ui/Button';
import { useState } from 'react';

interface OutputBoxProps {
    content: string;
    isLoading?: boolean;
    loadingText?: string;
}

const OutputBox: React.FC<OutputBoxProps> = ({
                                                 content,
                                                 isLoading = false,
                                                 loadingText = 'Processing...'
                                             }) => {
    const [copied, setCopied] = useState(false);

    const handleCopy = async () => {
        try {
            await navigator.clipboard.writeText(content);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        } catch (error) {
            console.error('Failed to copy text:', error);
        }
    };

    const formatContent = (text: string) => {
        // Convert markdown-like formatting to HTML
        return text
            .split('\n')
            .map((line, index) => {
                // Handle headers
                if (line.startsWith('**') && line.endsWith('**')) {
                    const headerText = line.slice(2, -2);
                    return (
                        <div key={index} className="font-semibold text-foreground mb-2 mt-3 first:mt-0">
                            {headerText}
                        </div>
                    );
                }

                // Handle bullet points
                if (line.startsWith('• ')) {
                    return (
                        <div key={index} className="ml-4 text-muted-foreground mb-1">
                            {line}
                        </div>
                    );
                }

                // Handle regular lines
                if (line.trim() === '') {
                    return <div key={index} className="h-2" />;
                }

                return (
                    <div key={index} className="text-muted-foreground mb-1 leading-relaxed">
                        {line}
                    </div>
                );
            });
    };

    if (isLoading) {
        return (
            <div className="bg-muted/30 rounded-lg p-6 space-y-4">
                <div className="flex items-center space-x-3">
                    <Loader2 className="w-5 h-5 animate-spin text-primary" />
                    <span className="text-sm font-medium text-foreground">{loadingText}</span>
                </div>
                <div className="space-y-2">
                    <div className="h-4 bg-muted rounded animate-pulse" />
                    <div className="h-4 bg-muted rounded animate-pulse w-3/4" />
                    <div className="h-4 bg-muted rounded animate-pulse w-1/2" />
                </div>
            </div>
        );
    }

    return (
        <div className="bg-muted/30 rounded-lg p-6 space-y-4">
            {/* Header with copy button */}
            <div className="flex items-center justify-between">
                <h3 className="font-medium text-foreground">AI Output</h3>
                <Button
                    onClick={handleCopy}
                    variant="ghost"
                    size="sm"
                    className="h-8 px-2"
                >
                    {copied ? (
                        <>
                            <Check className="w-3 h-3 mr-1" />
                            <span className="text-xs">Copied!</span>
                        </>
                    ) : (
                        <>
                            <Copy className="w-3 h-3 mr-1" />
                            <span className="text-xs">Copy</span>
                        </>
                    )}
                </Button>
            </div>

            {/* Content */}
            <div className="prose prose-sm max-w-none">
                <div className="text-sm space-y-1">
                    {formatContent(content)}
                </div>
            </div>

            {/* Footer */}
            <div className="pt-3 border-t border-border">
                <div className="flex items-center text-xs text-muted-foreground">
                    <div className="w-2 h-2 bg-green-500 rounded-full mr-2" />
                    Generated by Chrome's built-in AI
                </div>
            </div>
        </div>
    );
};

export default OutputBox;